### ISSUE TITLE
No Track Number

### ISSUE THREAD

**Issue by Beaker66** [idlesign/deflacue#2]
Hi
Seems no track number is being written to the output flac files..

Dave

**Comment by idlesign** [comment]
Hi.
Thank you. I'll try to check this out in a week.
May be you could expose .cue to reproduce?

**Comment by Beaker66** [comment]
Attached is a cue file for you

[Bonnie Tyler - The Ultimate Collection [Disc 1].zip](https://github.com/idlesign/deflacue/files/5494599/Bonnie.Tyler.-.The.Ultimate.Collection.Disc.1.zip)

**Comment by idlesign** [comment]
`2.0.1` is out, please give it a try.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
